# wallust 3.0 beta.*

backend = "kmeans"

color_space = "lab"

threshold = 10

palette = "dark16"


[templates]

hypr.template = 'templates/colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/colors-hyprland.conf'

rofi.template = 'templates/colors-rofi.rasi'
rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'

kitty.template = 'templates/colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty.conf'

waybar.template = 'templates/colors-waybar.css'
waybar.target = '~/.config/waybar/wallust/colors-waybar.css'

wlogout.template = 'templates/colors-waybar.css'
wlogout.target = '~/.config/wlogout/wallust/colors-wlogout.css'

dunst.template = 'templates/colors-dunst'
dunst.target = '~/.config/dunst/dunstrc.d/00-colors.conf'
