#!/bin/bash

aurPackages=(
    chili-sddm-theme
    dracula-gtk-theme
    dracula-icons-git
    jetbrains-toolbox
    nwg-displays
    paru
    paru-debug
    pyprland
    sddm-sugar-dark
    slack-desktop-wayland
    spotify
    trizen
    wallust-git
    wlogout
    discord_arch_electron
    betterdiscord-installer
    aws-cli-v2
)
